import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import ClientRootLayout from "./ClientRootLayout";
import Footer from "./_Component/Footer";
import NavigationBar from "./_Component/NavigationBar";
import Providers from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
          }}
        >
          <NavigationBar />
          <main style={{ flex: 1 }}>
            <Providers>
            <ClientRootLayout>{children}</ClientRootLayout>
            </Providers>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}